FROM ubuntu:22.04
# Install packages
RUN apt update && apt install \
    git \
    bash \
    curl \
    python3 \
    python3-pip \
    wget \
    curl \
    nodejs \
    npm -y

# Install AWSCLI
RUN pip install --upgrade pip && \
    pip install --upgrade awscli

CMD /bin/bash